### ISSUE TITLE
Using sbt-web-scalajs with single-project build

### ISSUE THREAD

**Issue by Krever** [vmunier/sbt-web-scalajs#34]
Hi,

I think it is currently not possible to use sbt-web-scalajs with single-project build. What I mean, is to have scalajs sources in our sbt-web project. Currently we need to have at least two projects: "sbt-web one" and "scalajs one". 

If I'm wrong or there is a good reason for such behaviour please tell me!

Thanks

**Comment by vmunier** [comment]
Hi,

Indeed, it is currently not possible to use sbt-web-scalajs within a single-project build.
You *cannot* do the following:
```
lazy val client: Project = project.settings(
  // self referencing the client project would cause an infinite loop when running compile
  scalaJSProjects := Seq(client),
  pipelineStages in Assets := Seq(scalaJSPipeline)
).enablePlugins(ScalaJSPlugin, ScalaJSWeb, SbtWeb)
```

The main goal of sbt-web-scalajs is to collect the Scala.js output files (`*-opt.js`, `*-launcher.js`, sourcemap files) using SbtWeb pipelines, so that a Server could send those files down to a browser.

Out of curiosity, why would you like to use sbt-web-scalajs without any server?

**Comment by Krever** [comment]
To generate fully static site and serve it outside of a project with some external server, e.g. Apache HTTP, nginx, Amazon S3, etc.

**Comment by joan38** [comment]
@Krever Yes it works:
```
lazy val myProject = crossProject
  .crossType(CrossType.Pure)
  .enablePlugins(SbtWeb, ScalaJSPlugin, ScalaJSWeb)
  .jsSettings(scalaJSUseMainModuleInitializer := true)
  .jvmSettings(
    WebKeys.packagePrefix in Assets := "public/",
    managedClasspath in Runtime += (packageBin in Assets).value,
    pipelineStages in Assets := Seq(scalaJSPipeline)
  )

lazy val myProjectJVM = myProject.jvm
  .settings(scalaJSProjects := Seq(myProjectJS))
lazy val myProjectJS = myProject.js
```
